### ISSUE TITLE
uhd630核显解决了吗？

### ISSUE THREAD

**Issue by bloodywinggithub** [SmallKi-d/ASUS-B460M-TUF-I5-10500ES-RX5700#3]
我这里是ipg里有gfx avg的曲线，但是进入final就崩溃或者无法选择渲染加速gpu

**Comment by SmallKi-d** [comment]
这个主板通病，要么核显，要么独显，不能共享显存，至于最新bios我还没测试

**Comment by bloodywinggithub** [comment]
奇怪的是videopro 可以看到核显加速，但是转码时仍然只跑cpu

**Comment by SmallKi-d** [comment]
已解决（刚高考完抱歉拖更这么久///w///）
